baseURL = 'https://kgole.github.io/new-personal-website/'
languageCode = 'en-us'
title = "Karteek's Website"
theme = 'chicago7'

[permalinks]
posts = "/posts/:year:month:day"

[markup]
[markup.highlight]
style = "bw"

[menu]
[[menu.header]]
name = "Contact"
url = "contact"
weight = 40

[[menu.header]]
name = "Posts"
url = "posts"
weight = 30

[[menu.header]]
name = "Projects"
url = "projects"
weight = 20

[[menu.header]]
name = "Home"
url = "/"
weight = 10

[params]
# Optional. The relative path to the site logo file within the `assets/` folder
logo = "logo2x.png"


# Web site author for copyrighting
author = "Karteek"

[params.social]
linkedin = "https://www.linkedin.com/in/karteekgole"

[taxonomies]
tags = "tags"
categories = "categories"
technologies = "technologies"