baseURL = "http://gohugo.io/"
title = "Chicago 7 Example"
languageCode = "en-us"
theme = "hugo-theme-chicago7"
pagination.pagerSize = 10

[permalinks]
posts = "/posts/:year:month:day"

[markup]
[markup.highlight]
style = "bw"

[menu]
[[menu.header]]
name = "About"
url = "about"
weight = 40

[[menu.header]]
name = "Posts"
url = "posts"
weight = 30

[[menu.header]]
name = "Projects"
url = "projects"
weight = 20

[[menu.header]]
name = "Home"
url = "/"
weight = 10

[params]
# Optional. The relative path to the site logo file within the `assets/` folder
logo = "logo.svg"

# Web site author for copyrighting
author = "Blog Author"

[params.social]
twitter = "https://x.com/example"
behance = "https://behance.net/yourprofile"
facebook = "https://facebook.com/yourprofile"
feed = "/index.xml"
